# 多智能体系统配置示例
# 这是一个简化的配置文件，易于理解和修改

# 系统基础设置
system_name: "智能多智能体系统"
debug: false
log_level: "INFO"
log_file: "logs/multi_agent.log"

# 数据库设置
database_type: "sqlite"
database_url: "sqlite:///data/multi_agent.db"

# LLM设置
llm_provider: "openai"
llm_model: "gpt-3.5-turbo"
llm_api_key: "${OPENAI_API_KEY}"  # 从环境变量读取
llm_base_url: null
llm_temperature: 0.7
llm_max_tokens: 1000
llm_timeout: 30

# 内存设置
memory_type: "in_memory"
memory_redis_url: "redis://localhost:6379"
memory_vector_url: "http://localhost:19530"
memory_max_size: 1000

# 协调器设置
coordinator_type: "sequential"
max_parallel_tasks: 5
task_timeout: 300
retry_attempts: 3

# 智能体设置
max_agents: 10
agent_timeout: 60

# 工具设置
tool_timeout: 30
max_tool_retries: 3

# 自定义设置
custom_settings:
  enable_metrics: true
  metrics_port: 8080
  health_check_interval: 30
  max_queue_size: 1000
