# 统一 YAML 配置（单一配置来源）
# 使用嵌套结构与 utils.config 对齐；可使用 ${ENV} 展开

system_name: "多智能体系统"
debug: false
log_level: "INFO"
log_file: null

# 组件配置
database:
  type: "sqlite"            # sqlite, postgresql, mysql
  host: "localhost"
  port: 5432
  database: "multi_agent"
  username: ""
  password: ""
  url: "sqlite:///multi_agent.db"
llm:
  provider: "openai"
  model: "qwen3-max-preview"
  api_key: ""
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"   # 若使用代理，设置为 https://your-proxy.example.com/v1（不要带 /chat/completions）
  temperature: 0.7
  max_tokens: 1000
  timeout: 30

memory:
  type: "in_memory"          # in_memory, redis, vector
  redis_url: "redis://localhost:6379"
  vector_db_url: "http://localhost:19530"
  max_memory_size: 1000

coordinator:
  type: "sequential"
  max_parallel_tasks: 5
  timeout: 300
  retry_attempts: 3

# 其他设置
max_agents: 10
agent_timeout: 60

tool_timeout: 30
max_tool_retries: 3

custom: {}
serper_api_key: "" 


